services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks: 
      - telehealth_network
    depends_on:
      - telehealth_db
    env_file:
      - .env   # <-- Explicitly load .env for the web service

  telehealth_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telehealth
    ports:
      - "5432:5432"
    networks:
      - telehealth_network
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  telehealth_network:
    driver: bridge